// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  contacts: dynamic(() => import("./Contacts")),
  content_index: dynamic(() => import("./ContentIndex")),
  eduction: dynamic(() => import("./Education")),
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./Hero2")),
  tech_list: dynamic(() => import("./TechList")),
};
